name: Publish Packages

on:
  push:
    tags:
    - v*

env:
  PACKAGES_SOLUTION_FILE_PATH: src/BuildingBlocks/Stuxy.BuildingBlocks.sln
  BUS_CORE_PROJECT_FILE_PATH: src/BuildingBlocks/Bus/Stuxy.Bus/Stuxy.Bus.csproj
  PACKAGES_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore ${{ env.PACKAGES_SOLUTION_FILE_PATH }}

    - name: Build
      run: dotnet build --configuration Release --no-restore ${{ env.PACKAGES_SOLUTION_FILE_PATH }}

    - name: Get Version
      id: version
      uses: battila7/get-version-action@v2

    - name: Pack
      run: dotnet pack --configuration Release --no-restore --no-build --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGES_OUTPUT_DIRECTORY }} ${{ env.PACKAGES_SOLUTION_FILE_PATH }}

    - name: Push
      run: dotnet nuget push ${{ env.PACKAGES_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate
